export const CATEGORIES_ACTION_TYPE = {
  FETCH_CATERGORIES_START: "category/FETCH_CATERGORIES_START",
  FETCH_CATERGORIES_SUCCESS: "category/FETCH_CATERGORIES_SUCCESS",
  FETCH_CATERGORIES_FAILED: "category/FETCH_CATERGORIES_FAILED",
};
